-- Wrap DDL in a conditional block so this script is safe to run against an
-- empty database (H2) or when tables don't exist yet. This uses H2's
-- BEGIN ATOMIC + EXECUTE IMMEDIATE pattern to run DDL only if the table is
-- present. That avoids failures like "Table ... not found" when Spring's
-- SQL initializer runs on a fresh DB.

BEGIN ATOMIC
  IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PESSOA_SUB_INSTITUICAO') > 0 THEN
    -- drop/add FK Pessoa -> Pessoa
    EXECUTE IMMEDIATE 'ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" DROP CONSTRAINT IF EXISTS "FKTM0RG6EW1RHIIWTF4FBNM2G8N"';
    EXECUTE IMMEDIATE 'ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" ADD CONSTRAINT "FKTM0RG6EW1RHIIWTF4FBNM2G8N" FOREIGN KEY("PESSOA_ID") REFERENCES "PUBLIC"."PESSOA"("ID") ON DELETE CASCADE';

    -- drop/add FK Pessoa -> Instituicao
    EXECUTE IMMEDIATE 'ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" DROP CONSTRAINT IF EXISTS "FKVTRVXLDTU33B2VYUPSKTEAYG"';
    EXECUTE IMMEDIATE 'ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" ADD CONSTRAINT "FKVTRVXLDTU33B2VYUPSKTEAYG" FOREIGN KEY("INSTITUICAO_ID") REFERENCES "PUBLIC"."INSTITUICAO"("ID") ON DELETE CASCADE';

    -- drop/add FK Pessoa -> Sub_instituicao
    EXECUTE IMMEDIATE 'ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" DROP CONSTRAINT IF EXISTS "FK33GG8R00EOKFXLWWV8GMA6NYK"';
    EXECUTE IMMEDIATE 'ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" ADD CONSTRAINT "FK33GG8R00EOKFXLWWV8GMA6NYK" FOREIGN KEY("SUB_INSTITUICAO_ID") REFERENCES "PUBLIC"."SUB_INSTITUICAO"("ID") ON DELETE CASCADE';
  END IF;
END;