-- schema.sql ? executado para criar/alterar estrutura (DDL) - na pasta resources

ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" 
  DROP CONSTRAINT IF EXISTS "FKTM0RG6EW1RHIIWTF4FBNM2G8N";
ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" 
  ADD CONSTRAINT "FKTM0RG6EW1RHIIWTF4FBNM2G8N" 
  FOREIGN KEY("PESSOA_ID") REFERENCES "PUBLIC"."PESSOA"("ID") ON DELETE CASCADE;

ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" 
  DROP CONSTRAINT IF EXISTS "FKVTRVXLDTU33B2VYUPSKTEAYG";
ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" 
  ADD CONSTRAINT "FKVTRVXLDTU33B2VYUPSKTEAYG" 
  FOREIGN KEY("INSTITUICAO_ID") REFERENCES "PUBLIC"."INSTITUICAO"("ID") ON DELETE CASCADE;

ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" 
  DROP CONSTRAINT IF EXISTS "FK33GG8R00EOKFXLWWV8GMA6NYK";
ALTER TABLE "PUBLIC"."PESSOA_SUB_INSTITUICAO" 
  ADD CONSTRAINT "FK33GG8R00EOKFXLWWV8GMA6NYK" 
  FOREIGN KEY("SUB_INSTITUICAO_ID") REFERENCES "PUBLIC"."SUB_INSTITUICAO"("ID") ON DELETE CASCADE;