name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        env:
          JASYPT_MASTER_KEY: ${{ secrets.JASYPT_MASTER_KEY }}
        run: mvn -B -DskipTests=false test

      - name: Run SpotBugs
        run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Run Checkstyle
        run: mvn -B org.apache.maven.plugins:maven-checkstyle-plugin:checkstyle

      - name: Run Checkstyle only on changed files (fail PR if new violations)
        run: |
          chmod +x scripts/checkstyle-diff.sh
          scripts/checkstyle-diff.sh

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html
